import 'package:flutter/material.dart';
import '../services/api_client.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key, required this.api}); final ApiClient api; @override State<HomeScreen> createState() => _HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
  Map<String,dynamic>? user; int tab = 0;
  @override void initState(){ super.initState(); load(); }
  Future<void> load() async { try { final u = await widget.api.me(); if(mounted) setState(()=>user=u); } catch (_) {} }
  void logout() async { await widget.api.logout(); if(mounted) Navigator.of(context).pop(); }
  @override Widget build(BuildContext context) { final pages = [HydraulicsPage(api: widget.api), CementingPage(api: widget.api), ProjectsPage(api: widget.api)]; return Scaffold(
    appBar: AppBar(title: const Text('PETRONEXA', style: TextStyle(fontWeight: FontWeight.w900, letterSpacing: 1.5)), actions:[IconButton(onPressed: logout, icon: const Icon(Icons.logout))]),
    drawer: Drawer(child: ListView(padding: EdgeInsets.zero, children:[DrawerHeader(child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children:[Image.asset('assets/petronexa_logo.png', width:210, fit:BoxFit.contain), const SizedBox(height:6), Text(user?['email']?.toString() ?? '')])), ListTile(leading:const Icon(Icons.water_drop), title:const Text('Hydraulics'), onTap:(){setState(()=>tab=0);Navigator.pop(context);}), ListTile(leading:const Icon(Icons.construction), title:const Text('Cementing'), onTap:(){setState(()=>tab=1);Navigator.pop(context);}), ListTile(leading:const Icon(Icons.folder), title:const Text('Projects'), onTap:(){setState(()=>tab=2);Navigator.pop(context);})])), body: pages[tab]); }
}

class HydraulicsPage extends StatefulWidget { const HydraulicsPage({super.key,required this.api}); final ApiClient api; @override State<HydraulicsPage> createState()=>_HydraulicsPageState(); }
class _HydraulicsPageState extends State<HydraulicsPage>{ final flow=TextEditingController(text:'550'), depth=TextEditingController(text:'10000'), mw=TextEditingController(text:'12.5'), pv=TextEditingController(text:'22'), yp=TextEditingController(text:'16'); Map<String,dynamic>? result; String? error;
Future<void> run() async { try { final r=await widget.api.hydraulics({'flow_rate_gpm':double.parse(flow.text),'total_depth_ft':double.parse(depth.text),'surface_mud_weight_ppg':double.parse(mw.text),'plastic_viscosity_cp':double.parse(pv.text),'yield_point_lb_100ft2':double.parse(yp.text)}); setState(()=>result=r); } catch(e){setState(()=>error=e.toString());} }
Widget field(String label,TextEditingController c)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[const Text('Hydraulics Matrix',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('Run the existing Python engineering engine through the PetroNexa API.',style:TextStyle(color:Colors.white60)),const SizedBox(height:20),field('Flow rate (GPM)',flow),field('Total depth (ft)',depth),field('Mud weight (ppg)',mw),field('Plastic viscosity (cP)',pv),field('Yield point (lb/100 ft²)',yp),FilledButton.icon(onPressed:run,icon:const Icon(Icons.calculate),label:const Text('Run calculation')),if(error!=null)Text(error!,style:const TextStyle(color:Colors.redAccent)),if(result!=null)...[const SizedBox(height:20),_result('ECD',result!['physics_results']?['equivalent_circulating_density_ecd_ppg']),_result('Standpipe pressure',result!['physics_results']?['standpipe_pressure_psi']),_result('Diagnostics',result!['diagnostics'])]]);
Widget _result(String a,dynamic b)=>Card(child:ListTile(title:Text(a),subtitle:Text(b?.toString()??'—')));
}

class CementingPage extends StatefulWidget { const CementingPage({super.key,required this.api}); final ApiClient api; @override State<CementingPage> createState()=>_CementingPageState(); }
class _CementingPageState extends State<CementingPage>{ final hole=TextEditingController(text:'8.5'), casing=TextEditingController(text:'7.0'), length=TextEditingController(text:'5000'), wash=TextEditingController(text:'15'); Map<String,dynamic>? result; String? error;
Future<void> run() async { try { final r=await widget.api.cementing({'hole_diameter_in':double.parse(hole.text),'casing_od_in':double.parse(casing.text),'casing_id_in':6.276,'interval_length_ft':double.parse(length.text),'washout_factor_pct':double.parse(wash.text),'shoe_track_length_ft':40.0,'lead_slurry_density_ppg':12.5,'tail_slurry_density_ppg':15.8,'spacer_density_ppg':11.0,'displacement_fluid_density_ppg':10.0,'tail_slurry_length_ft':500.0,'bht_fahrenheit':180.0}); setState(()=>result=r); } catch(e){setState(()=>error=e.toString());} }
Widget f(String l,TextEditingController c)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));
@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[const Text('Primary Cementing',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:18),f('Hole diameter (in)',hole),f('Casing OD (in)',casing),f('Interval length (ft)',length),f('Washout (%)',wash),FilledButton.icon(onPressed:run,icon:const Icon(Icons.calculate),label:const Text('Design cement job')),if(error!=null)Text(error!,style:const TextStyle(color:Colors.redAccent)),if(result!=null)...[const SizedBox(height:20),_r('Lead slurry volume (bbl)',result!['lead_slurry_volume_bbl']),_r('Tail slurry volume (bbl)',result!['tail_slurry_volume_bbl']),_r('Plug bumping pressure (psi)',result!['recommended_plug_bumping_pressure_psi'])]]);
Widget _r(String a,dynamic b)=>Card(child:ListTile(title:Text(a),subtitle:Text(b?.toString()??'—')));
}

class ProjectsPage extends StatefulWidget { const ProjectsPage({super.key,required this.api}); final ApiClient api; @override State<ProjectsPage> createState()=>_ProjectsPageState(); }
class _ProjectsPageState extends State<ProjectsPage>{ Future<List<dynamic>>? future; @override void initState(){super.initState();future=widget.api.projects();} @override Widget build(BuildContext c)=>FutureBuilder<List<dynamic>>(future:future,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('Unable to load projects: ${s.error}'));final items=s.data??[];return ListView(padding:const EdgeInsets.all(18),children:[const Text('Projects',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:12),if(items.isEmpty)const Text('No projects yet. Project management is ready for the next module.'),...items.map((p)=>Card(child:ListTile(title:Text(p['name'].toString()),subtitle:Text('${p['well_name'] ?? ''} • ${p['field_name'] ?? ''}'))))]);});}
