import io
import os
from datetime import datetime, timezone
from typing import Dict, Any, Optional

from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, Line, String
from reportlab.lib.utils import ImageReader


# ============================
# CUSTOM CANVAS (Header, Watermark, Footer)
# ============================
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

        self.logo_image = None
        script_dir = os.path.dirname(os.path.abspath(__file__))
        cwd = os.getcwd()
        possible_paths = [
            os.path.join(script_dir, "logo.png"),
            os.path.join(script_dir, "assets", "logo.png"),
            os.path.join(cwd, "logo.png"),
            os.path.join(cwd, "assets", "logo.png"),
            "logo.png",
        ]
        for path in possible_paths:
            if os.path.exists(path):
                try:
                    self.logo_image = ImageReader(path)
                    break
                except Exception:
                    continue

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def _draw_watermark(self):
        if self.logo_image is None:
            self.saveState()
            self.setFont("Helvetica-Bold", 42)
            self.setFillColor(colors.HexColor("#94A3B8"))
            self.setFillAlpha(0.08)
            self.drawCentredString(306, 400, "PETRONEXA")
            self.restoreState()
            return

        page_width, page_height = letter
        wm_width = 180
        img_w, img_h = self.logo_image.getSize()
        aspect = img_h / float(img_w)
        wm_height = wm_width * aspect

        x = (page_width - wm_width) / 2
        y = (page_height - wm_height) / 2

        self.saveState()
        self.setFillAlpha(0.10)
        self.drawImage(
            self.logo_image, x, y,
            width=wm_width, height=wm_height,
            preserveAspectRatio=True, mask="auto"
        )
        self.restoreState()

    def _draw_header_logo(self):
        if self.logo_image is None:
            return
        page_width, page_height = letter
        logo_width = 48
        img_w, img_h = self.logo_image.getSize()
        aspect = img_h / float(img_w)
        logo_height = logo_width * aspect

        x = page_width - 54 - logo_width
        y = page_height - 48 - logo_height

        self.saveState()
        self.drawImage(
            self.logo_image, x, y,
            width=logo_width, height=logo_height,
            preserveAspectRatio=True, mask="auto"
        )
        self.restoreState()

    def _draw_page_decorations(self, page_count: int):
        self._draw_watermark()
        self.saveState()
        self._draw_header_logo()

        if self._pageNumber > 1:
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(colors.HexColor("#64748B"))
            self.drawString(54, 752, "PetroNexa  —  ENGINEERING TECHNICAL REPORT")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.6)
            self.line(54, 744, 558, 744)

        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.8)
        self.line(54, 42, 558, 42)

        self.setFont("Helvetica", 7.5)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(54, 28, "Generated by PetroNexa")
        self.drawCentredString(306, 28, "CONFIDENTIAL  ·  DRILLING ENGINEERING DIVISION")
        self.drawRightString(558, 28, f"Page {self._pageNumber} of {page_count}")

        self.restoreState()


# ============================
# DATA-DRIVEN PRESSURE WINDOW CHART
# ============================
def create_pressure_window_chart(pore_ppg: float, ecd_ppg: float, frac_ppg: float) -> Drawing:
    """
    Generates a dynamic visual representation of the hydraulic window.
    Calculates scale boundaries dynamically from inputs to prevent clipping.
    """
    d = Drawing(450, 110)
    
    # Background Box
    d.add(Rect(0, 0, 450, 110, fillColor=colors.HexColor("#F8FAFC"), strokeColor=colors.HexColor("#CBD5E1"), strokeWidth=0.8))

    # Calculate dynamic scale bounds with 1.0 ppg padding
    min_val = max(0.0, min(pore_ppg, ecd_ppg, frac_ppg) - 1.0)
    max_val = max(pore_ppg, ecd_ppg, frac_ppg) + 1.0
    
    width_px = 370.0
    start_x = 40.0

    def val_to_x(v: float) -> float:
        if max_val == min_val:
            return start_x + (width_px / 2.0)
        return start_x + ((v - min_val) / (max_val - min_val)) * width_px

    pore_x = val_to_x(pore_ppg)
    frac_x = val_to_x(frac_ppg)
    ecd_x = val_to_x(ecd_ppg)

    # Zones
    d.add(Rect(start_x, 25, max(0, pore_x - start_x), 60, fillColor=colors.HexColor("#FEE2E2"), strokeColor=colors.transparent)) # Underbalanced
    d.add(Rect(pore_x, 25, max(0, frac_x - pore_x), 60, fillColor=colors.HexColor("#DCFCE7"), strokeColor=colors.transparent)) # Safe Window
    d.add(Rect(frac_x, 25, max(0, (start_x + width_px) - frac_x), 60, fillColor=colors.HexColor("#FEE2E2"), strokeColor=colors.transparent)) # Losses/Frac

    # Marker Lines
    d.add(Line(pore_x, 20, pore_x, 90, strokeColor=colors.HexColor("#DC2626"), strokeWidth=1.5))
    d.add(Line(frac_x, 20, frac_x, 90, strokeColor=colors.HexColor("#DC2626"), strokeWidth=1.5))
    
    # ECD Marker Line & Indicator
    d.add(Line(ecd_x, 15, ecd_x, 95, strokeColor=colors.HexColor("#2563EB"), strokeWidth=2.5))

    # Labels
    d.add(String(max(start_x, pore_x - 20), 93, f"Pore: {pore_ppg:.2f}", fontName="Helvetica-Bold", fontSize=7.5, fillColor=colors.HexColor("#991B1B")))
    d.add(String(min(start_x + width_px - 35, frac_x - 10), 93, f"Frac: {frac_ppg:.2f}", fontName="Helvetica-Bold", fontSize=7.5, fillColor=colors.HexColor("#991B1B")))
    d.add(String(max(start_x, min(start_x + width_px - 35, ecd_x - 15)), 5, f"ECD: {ecd_ppg:.2f}", fontName="Helvetica-Bold", fontSize=8, fillColor=colors.HexColor("#1E3A8A")))

    return d


# ============================
# MAIN PDF GENERATOR
# ============================
def generate_pdf_payload(
    project_metadata: Dict[str, Any],
    physics_results: Dict[str, Any],
    diagnostic_results: Dict[str, Any],
    engineer_name: str = "Peter Prempeh",
    cementing_results: Optional[Dict[str, Any]] = None
) -> io.BytesIO:

    # 1. Strict Boundary Validation
    pore_limit = diagnostic_results.get("pore_limit")
    frac_limit = diagnostic_results.get("frac_limit")

    if pore_limit is None or frac_limit is None:
        raise ValueError(
            "Diagnostic results must include 'pore_limit' and 'frac_limit' "
            "before generating the engineering PDF."
        )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=58,
        bottomMargin=58
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title", fontName="Helvetica-Bold", fontSize=20, leading=24,
        textColor=colors.HexColor("#0F172A"), spaceAfter=2
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", fontName="Helvetica", fontSize=10.5, leading=14,
        textColor=colors.HexColor("#2563EB"), spaceAfter=14
    )
    h1_style = ParagraphStyle(
        "H1", fontName="Helvetica-Bold", fontSize=11.5, leading=15,
        textColor=colors.HexColor("#0F172A"), spaceBefore=16, spaceAfter=6
    )
    body_style = ParagraphStyle(
        "Body", fontName="Helvetica", fontSize=8.5, leading=12,
        textColor=colors.HexColor("#334155")
    )
    bold_body = ParagraphStyle(
        "BodyBold", fontName="Helvetica-Bold", fontSize=8.5, leading=12,
        textColor=colors.HexColor("#1E293B")
    )
    header_white_style = ParagraphStyle(
        "HeaderWhite", fontName="Helvetica-Bold", fontSize=8.5, leading=12,
        textColor=colors.white
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer", fontName="Helvetica-Oblique", fontSize=7.5, leading=10,
        textColor=colors.HexColor("#64748B"), spaceBefore=4
    )

    elements = []

    # ---- Title ----
    elements.append(Paragraph("PetroNexa", title_style))
    elements.append(Paragraph("PetroNexa Engineering Technical Report", subtitle_style))

    # ---- Metadata ----
    now_utc = datetime.now(timezone.utc)
    now_str = now_utc.strftime("%Y-%m-%d %H:%M UTC")
    report_id = f"PNX-DRL-{now_utc.strftime('%Y%m%d-%H%M')}"
    td_val = physics_results.get("total_depth_ft", 0.0)
    flow_val = physics_results.get("flow_rate_gpm", 0.0)

    meta_data = [
        [
            Paragraph("<b>Project Asset</b>", body_style),
            Paragraph(str(project_metadata.get("name", "N/A")), body_style),
            Paragraph("<b>Rig</b>", body_style),
            Paragraph(str(project_metadata.get("rig_name", "Rig-05")), body_style),
        ],
        [
            Paragraph("<b>Wellbore Depth</b>", body_style),
            Paragraph(f"{td_val:,.0f} ft MD", body_style),
            Paragraph("<b>Lead Engineer</b>", body_style),
            Paragraph(engineer_name, body_style),
        ],
        [
            Paragraph("<b>Operating Client</b>", body_style),
            Paragraph(str(project_metadata.get("company", "Enterprise Hydrocarbons Corp")), body_style),
            Paragraph("<b>Report ID</b>", body_style),
            Paragraph(report_id, body_style),
        ],
        [
            Paragraph("<b>Flow Rate</b>", body_style),
            Paragraph(f"{flow_val:.0f} GPM", body_style),
            Paragraph("<b>Generated</b>", body_style),
            Paragraph(now_str, body_style),
        ],
    ]
    t_meta = Table(meta_data, colWidths=[95, 155, 95, 155])
    t_meta.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#E2E8F0")),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#F1F5F9")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.extend([t_meta, Spacer(1, 12)])

    # ---- Executive Summary ----
    severity = diagnostic_results.get("severity", "GREEN")
    if severity == "GREEN":
        status_text = "STABLE OPERATIONAL GRADIENT"
        status_color = "#166534"
    elif severity in ["YELLOW", "WARNING"]:
        status_text = "WARNING – ELEVATED RISK"
        status_color = "#B45309"
    else:
        status_text = "CRITICAL HYDRAULIC BREACH"
        status_color = "#991B1B"

    diag_text = diagnostic_results.get(
        "detailed_diagnosis",
        diagnostic_results.get("message", "Nominal operational parameters confirmed.")
    )

    summary_box = [
        [Paragraph("<b>Hydraulic Operating Status</b>", body_style),
         Paragraph(f'<font color="{status_color}"><b>{status_text}</b></font>', body_style)],
        [Paragraph("<b>Matched Hazard</b>", body_style),
         Paragraph(diagnostic_results.get("matched_hazard", "None"), body_style)],
        [Paragraph("<b>Automated Engineering Diagnosis</b>", body_style),
         Paragraph(diag_text, body_style)],
    ]
    t_summary = Table(summary_box, colWidths=[140, 360])
    t_summary.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1.2, colors.HexColor("#0F172A")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F1F5F9")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    elements.extend([Paragraph("EXECUTIVE SUMMARY", h1_style), t_summary, Spacer(1, 8)])

    # ---- Hydraulics Summary ----
    elements.append(Paragraph("1. Primary Mechanical Hydraulics Summary", h1_style))
    ecd = physics_results.get("ecd_ppg", 0.0)
    ann_dp = physics_results.get("total_annular_dp_psi", 0.0)
    bhp = physics_results.get("bottom_hole_pressure_psi", 0.0)
    hydrostatic = physics_results.get("hydrostatic_pressure_psi", 0.0)

    ecd_status = "PASS" if (pore_limit <= ecd <= frac_limit) else "EXCURSION"
    ann_dp_status = diagnostic_results.get("annular_dp_status", "CALCULATED")

    comp_rows = [
        [
            Paragraph("Metric Parameter", header_white_style),
            Paragraph("Calculated Value", header_white_style),
            Paragraph("Configured Limit / Range", header_white_style),
            Paragraph("Status", header_white_style),
        ],
        [
            Paragraph("Equivalent Circulating Density (ECD)", body_style),
            Paragraph(f"{ecd:.3f} ppg", body_style),
            Paragraph(f"{pore_limit:.2f} – {frac_limit:.2f} ppg", body_style),
            Paragraph(ecd_status, bold_body),
        ],
        [
            Paragraph("Bottom Hole Pressure (BHP)", body_style),
            Paragraph(f"{bhp:,.1f} psi", body_style),
            Paragraph("Hydrostatic + Annular DP", body_style),
            Paragraph("NOMINAL", bold_body),
        ],
        [
            Paragraph("Hydrostatic Pressure", body_style),
            Paragraph(f"{hydrostatic:,.1f} psi", body_style),
            Paragraph("Static Mud Column", body_style),
            Paragraph("NOMINAL", bold_body),
        ],
        [
            Paragraph("Total Annular Pressure Drop", body_style),
            Paragraph(f"{ann_dp:,.1f} psi", body_style),
            Paragraph("Dynamic Friction Loss", body_style),
            Paragraph(ann_dp_status, bold_body),
        ],
    ]
    t_comp = Table(comp_rows, colWidths=[185, 105, 120, 90])
    t_comp.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#FFFFFF"), colors.HexColor("#F8FAFC")]),
    ]))
    elements.extend([t_comp, Spacer(1, 10)])

    # ---- Dynamic Pressure Profile Chart ----
    elements.append(Paragraph("2. Pressure Profile Window", h1_style))
    elements.append(create_pressure_window_chart(pore_limit, ecd, frac_limit))
    elements.append(Spacer(1, 12))

    # ---- Cementing (Optional) ----
    if cementing_results:
        elements.append(Paragraph("3. Primary Cementing Job Summary", h1_style))
        c_data = [
            [Paragraph("Parameter", header_white_style), Paragraph("Value", header_white_style)],
            [Paragraph("Lead Slurry Volume", body_style), f"{cementing_results.get('lead_slurry_volume_bbl', 0.0):.2f} bbl"],
            [Paragraph("Tail Slurry Volume", body_style), f"{cementing_results.get('tail_slurry_volume_bbl', 0.0):.2f} bbl"],
            [Paragraph("Spacer Volume", body_style), f"{cementing_results.get('spacer_volume_bbl', 0.0):.2f} bbl"],
            [Paragraph("Displacement Volume", body_style), f"{cementing_results.get('displacement_volume_bbl', 0.0):.2f} bbl"],
            [Paragraph("Recommended Plug Bumping Pressure", body_style),
             f"{cementing_results.get('recommended_plug_bumping_pressure_psi', 0.0):.1f} psi"],
        ]
        t_cement = Table(c_data, colWidths=[260, 240])
        t_cement.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#FFFFFF"), colors.HexColor("#F8FAFC")]),
        ]))
        elements.append(t_cement)
        elements.append(Spacer(1, 8))

        additives = cementing_results.get("suggested_additives", [])
        if additives:
            elements.append(Paragraph("Suggested Cement Additives", h1_style))
            for add in additives:
                if isinstance(add, dict):
                    name = add.get("name", "Additive")
                    cat = add.get("category", "General")
                    desc = add.get("description", "")
                    elements.append(Paragraph(f"• <b>{name}</b> ({cat}) – {desc}", body_style))
            
            elements.append(Paragraph(
                "<i>Note: Additive suggestions are preliminary engineering heuristics and require verification against cement-service-company laboratory testing and approved job design.</i>",
                disclaimer_style
            ))
            elements.append(Spacer(1, 8))

    # ---- Recommendations & Sign-off ----
    elements.append(Paragraph("4. Engineering Action Recommendations & Sign-Off", h1_style))
    recs = diagnostic_results.get(
        "actionable_recommendations",
        [diagnostic_results.get("recommendation", "Maintain standard operations inside safe pressure window.")]
    )
    if isinstance(recs, str):
        recs = [recs]

    for rec in recs:
        elements.append(Paragraph(f"• {rec}", body_style))

    elements.append(Spacer(1, 22))
    sig_line = "________________________________"
    sig_data = [
        [
            Paragraph(
                f"<b>Prepared By</b><br/><br/>{sig_line}<br/>Lead Engineer: {engineer_name}",
                body_style
            ),
            Paragraph(
                f"<b>Approved By</b><br/><br/>{sig_line}<br/>Rig Superintendent",
                body_style
            ),
        ]
    ]
    t_sig = Table(sig_data, colWidths=[250, 250])
    t_sig.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_sig)

    doc.build(elements, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer
