"""
Professional PDF Engineering Report Engine for PetroNexa.
"""
import io
from typing import Dict, Any, Optional
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


def generate_pdf_payload(
    project_metadata: Dict[str, str],
    physics_results: Dict[str, Any],
    diagnostic_results: Optional[Dict[str, Any]] = None,
    engineer_name: str = "Drilling Engineer",
    cementing_results: Optional[Dict[str, Any]] = None,
) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()

    # Custom typography
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0F172A'),
        fontName='Helvetica-Bold',
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        'SubTitle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#475569'),
        spaceAfter=12,
    )
    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#1E293B'),
        fontName='Helvetica-Bold',
        spaceBefore=10,
        spaceAfter=6,
    )
    body_style = ParagraphStyle('BodyText', parent=styles['Normal'], fontSize=9, leading=13)

    story = []

    # Title Banner
    story.append(Paragraph("PETRONEXA ENGINEERING ANALYSIS", title_style))
    story.append(Paragraph(f"Well Operations Report | Generated by: {engineer_name}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563EB'), spaceAfter=12))

    # Well Header Information Table
    meta_data = [
        ["Project / Well:", project_metadata.get("name", "N/A"), "Field:", project_metadata.get("field_name", "N/A")],
        ["Rig Name:", project_metadata.get("rig_name", "N/A"), "Company:", project_metadata.get("company", "PetroNexa")],
    ]
    t_meta = Table(meta_data, colWidths=[100, 170, 70, 200])
    t_meta.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#334155')),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 10))

    # Diagnostic Summary Status Box
    if diagnostic_results:
        sev = diagnostic_results.get("severity", "GREEN")
        box_bg = colors.HexColor('#DC2626') if sev == "RED" else (colors.HexColor('#D97706') if sev == "YELLOW" else colors.HexColor('#16A34A'))
        
        diag_data = [
            [Paragraph(f"<b>OPERATIONAL STATUS: {sev}</b> — {diagnostic_results.get('matched_hazard', 'Normal')}", ParagraphStyle('Diag', parent=body_style, textColor=colors.white))]
        ]
        t_diag = Table(diag_data, colWidths=[540])
        t_diag.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), box_bg),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(t_diag)
        story.append(Spacer(1, 10))

    # Executive Summary Metrics Table
    story.append(Paragraph("Hydraulics & Wellbore Summary", section_style))
    summary_data = [
        ["Parameter", "Value", "Unit", "Parameter", "Value", "Unit"],
        ["Flow Rate", f"{physics_results.get('flow_rate_gpm', 0.0):.1f}", "GPM", "Surface Mud Weight", f"{physics_results.get('surface_mud_weight_ppg', 0.0):.2f}", "ppg"],
        ["Total Depth (MD)", f"{physics_results.get('total_depth_ft', 0.0):.1f}", "ft", "Bottomhole ECD", f"{physics_results.get('equivalent_circulating_density_ecd_ppg', 0.0):.3f}", "ppg"],
        ["TVD Depth", f"{physics_results.get('true_vertical_depth_ft', 0.0):.1f}", "ft", "Standpipe Pressure", f"{physics_results.get('standpipe_pressure_spp_psi', 0.0):.1f}", "psi"],
        ["Plastic Viscosity", f"{physics_results.get('plastic_viscosity_cp', 0.0):.1f}", "cP", "Yield Point", f"{physics_results.get('yield_point_lb_100ft2', 0.0):.1f}", "lb/100ft²"],
    ]

    t_summary = Table(summary_data, colWidths=[120, 70, 80, 120, 70, 80])
    t_summary.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E293B')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8FAFC')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(t_summary)
    story.append(Spacer(1, 12))

    # Segment Breakdown Table
    story.append(Paragraph("Segment Pressure Breakdown", section_style))
    segment_data = [["Seg #", "Name", "Length (ft)", "Ann. Vel (fpm)", "Ann. Loss (psi)", "Regime", "Local ECD (ppg)"]]
    for seg in physics_results.get("segment_breakdown", []):
        segment_data.append([
            str(seg.get("segment_index")),
            str(seg.get("segment_name")),
            f"{seg.get('length_ft', 0.0):.1f}",
            f"{seg.get('annular_velocity_fpm', 0.0):.1f}",
            f"{seg.get('annular_loss_psi', 0.0):.1f}",
            str(seg.get("annular_flow_regime")),
            f"{seg.get('local_ecd_ppg', 0.0):.3f}",
        ])

    t_seg = Table(segment_data, colWidths=[40, 110, 70, 80, 80, 80, 80])
    t_seg.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#334155')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(t_seg)

    # Optional Cementing Summary Section
    if cementing_results:
        story.append(Spacer(1, 12))
        story.append(Paragraph("Cementing Job Design Summary", section_style))
        cem_data = [
            ["Parameter", "Value", "Unit"],
            ["Lead Slurry Volume", f"{cementing_results.get('lead_slurry_volume_bbl', 0.0):.2f}", "bbl"],
            ["Tail Slurry Volume", f"{cementing_results.get('tail_slurry_volume_bbl', 0.0):.2f}", "bbl"],
            ["Spacer Volume", f"{cementing_results.get('spacer_volume_bbl', 0.0):.2f}", "bbl"],
            ["Displacement Volume", f"{cementing_results.get('displacement_volume_bbl', 0.0):.2f}", "bbl"],
            ["Differential Hydrostatic", f"{cementing_results.get('differential_hydrostatic_psi', 0.0):.1f}", "psi"],
            ["Plug Bumping Pressure", f"{cementing_results.get('recommended_plug_bumping_pressure_psi', 0.0):.1f}", "psi"],
        ]
        t_cem = Table(cem_data, colWidths=[200, 150, 190])
        t_cem.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#475569')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]))
        story.append(t_cem)

    doc.build(story)
    buffer.seek(0)
    return buffer
